default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>

development:
  <<: *default
  database: webcv_development

production:
  <<: *default
  database: webcv_production
