development:
  adapter: postgresql
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASS'] %>
  database: webcv_development
  encoding: utf8

test:
  adapter: postgresql
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASS'] %>
  database: webcv_development
  encoding: utf8
